version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn test
artifacts:
  files:
    - target/CostBenefitBackend-0.0.1-SNAPSHOT.jar
  discard-paths: yes
